# LAB 3: LÀM SẠCH DỮ LIỆU (DATA CLEANING)
**Học phần:** Dữ liệu lớn (Big Data)  
**Mã số sinh viên:** 26410022  

---

## I – LÝ THUYẾT & TỔNG QUAN
Làm sạch dữ liệu là một bước tối quan trọng trong bất kỳ dự án máy học và phân tích dữ liệu lớn nào. 
Trong bài thực hành này, chúng ta tìm hiểu 2 khối kiến thức cốt lõi:
1. **Thao tác chuẩn hóa cấu trúc dữ liệu bảng (Column & Header Manipulations):**
   - Cách đọc dữ liệu từ GitHub Raw trên Google Colab.
   - Tra cứu cột trong dữ liệu.
   - Đổi tên cột, chuẩn hóa viết hoa/thường, ký tự gạch dưới thay thế khoảng trắng.
   - Lọc chọn cột bằng các phương thức như `df.filter`, `loc`, `str.endswith`, phủ định `isin`.
2. **Xử lý giá trị bị thiếu (Missing Values Imputation & Cleaning):**
   - Đọc dữ liệu nhận diện cả các định dạng khuyết thiếu phi chuẩn (`na_values=['n/a', 'na', '--']`).
   - Kiểm tra và tính toán tổng số lượng khuyết thiếu.
   - Điền giá trị hằng số cố định (`fillna(126)`) và giá trị thống kê trung vị (`median`).

---
## II – TẢI DATASET TRỰC TIẾP TRÊN GOOGLE COLAB

Dùng GitHub Raw để đọc CSV trong notebook, không cần mount Google Drive.

In [ ]:
import pandas as pd
import numpy as np

DATASET_BASE_URL = "https://raw.githubusercontent.com/shizziio/uit-DS200.G11.CN2.TTNT/main/datasets/lab3"
print("Đọc dataset trực tiếp từ GitHub Raw; không cần mount Google Drive.")

---
## III – THỰC HÀNH CÁC THAO TÁC TRÊN CỘT DỮ LIỆU
Chúng ta sử dụng bộ dữ liệu mẫu `sample_data.csv` gồm thông tin nhân sự/khách hàng tương ứng với phần hướng dẫn thực hành trên Google Colab.

In [2]:
# Đọc bộ dữ liệu mẫu
df = pd.read_csv(f'{DATASET_BASE_URL}/sample_data.csv')
df.head()

,First Name,Last name,Age,SALARY,STREET Address1,STREET Address2,STREET Address3,email
0,Joel,Padilla,10/28/2019,0.32,431-6530 Eu Rd.,364-2264 Augue Rd.,P.O. Box 864 3882 Orci Street,eu@nibh.com
1,Fritz,Tyler,09/27/2019,0.91,979-2228 Vel Ave,P.O. Box 864 3882 Orci Street,9865 Eu Av.,est.ac.mattis@malesuadafringilla.net
2,Wing,Phelps,02/18/2019,0.15,Ap #377-2267 Ac Av.,Ap #545-5786 Pulvinar Ave,Ap #973-5781 Sagittis Avenue,dolor@cubilia.net
3,Ryan,Ross,05/21/2019,0.97,634-7858 Id Road,907-8824 Fringilla Ave,318-5271 In Ave,interdum.libero.dui@vitaeerat.com
4,Drake,Day,01/09/2020,0.38,999-8221 Tempor St.,297-6939 Turpis Ave,P.O. Box 638 6932 Laoreet Rd.,nulla.Integer.vulputate@liberoat.ca

### 1. Chuẩn hóa viết thường, in hoa, viết hoa đầu từ tên cột

In [3]:
# Thay đổi tiêu đề các dòng thành chữ thường
df.columns.str.lower()

Index(['first name', 'last name', 'age', 'salary', 'street address1',
       'street address2', 'street address3', 'email'],
      dtype='str')

In [4]:
# Thay đổi thành chữ in hoa
df.columns.str.upper()

Index(['FIRST NAME', 'LAST NAME', 'AGE', 'SALARY', 'STREET ADDRESS1',
       'STREET ADDRESS2', 'STREET ADDRESS3', 'EMAIL'],
      dtype='str')

In [5]:
# Ký tự đầu in hoa
df.columns.str.title()

Index(['First Name', 'Last Name', 'Age', 'Salary', 'Street Address1',
       'Street Address2', 'Street Address3', 'Email'],
      dtype='str')

### 2. Thay thế ký tự khoảng trắng bằng dấu gạch dưới `_`

In [6]:
# Thay thế khoảng trắng bằng dấu _
df.columns.str.replace(' ', '_')

Index(['First_Name', 'Last_name', 'Age', 'SALARY', 'STREET_Address1',
       'STREET_Address2', 'STREET_Address3', 'email'],
      dtype='str')

### 3. Đổi tên cột (`rename` và gán trực tiếp qua `columns.values`)

In [7]:
# Thay đổi tên cột Age thành Date of Birth
df = df.rename(columns={'Age': 'Date of Birth'})
df.head()

,First Name,Last name,Date of Birth,SALARY,STREET Address1,STREET Address2,STREET Address3,email
0,Joel,Padilla,10/28/2019,0.32,431-6530 Eu Rd.,364-2264 Augue Rd.,P.O. Box 864 3882 Orci Street,eu@nibh.com
1,Fritz,Tyler,09/27/2019,0.91,979-2228 Vel Ave,P.O. Box 864 3882 Orci Street,9865 Eu Av.,est.ac.mattis@malesuadafringilla.net
2,Wing,Phelps,02/18/2019,0.15,Ap #377-2267 Ac Av.,Ap #545-5786 Pulvinar Ave,Ap #973-5781 Sagittis Avenue,dolor@cubilia.net
3,Ryan,Ross,05/21/2019,0.97,634-7858 Id Road,907-8824 Fringilla Ave,318-5271 In Ave,interdum.libero.dui@vitaeerat.com
4,Drake,Day,01/09/2020,0.38,999-8221 Tempor St.,297-6939 Turpis Ave,P.O. Box 638 6932 Laoreet Rd.,nulla.Integer.vulputate@liberoat.ca

In [8]:
# Đổi tên cột thứ 8 (chỉ số 7) thành Email Address
df.columns.values[7] = 'Email Address'
df.columns

Index(['First Name', 'Last name', 'Date of Birth', 'SALARY', 'STREET Address1',
       'STREET Address2', 'STREET Address3', 'Email Address'],
      dtype='str')

### 4. Lọc chọn các cột theo điều kiện

In [9]:
# Chọn tất cả trừ điều kiện (!= 'SALARY')
df.columns[df.columns != 'SALARY']

Index(['First Name', 'Last name', 'Date of Birth', 'STREET Address1',
       'STREET Address2', 'STREET Address3', 'Email Address'],
      dtype='str')

In [10]:
# Chọn tất cả trừ điều kiện dùng phủ định isin
df.loc[:, ~df.columns.isin(['SALARY'])].columns

Index(['First Name', 'Last name', 'Date of Birth', 'STREET Address1',
       'STREET Address2', 'STREET Address3', 'Email Address'],
      dtype='str')

In [11]:
# Chọn tên cột chứa ký tự trong điều kiện (df.filter like)
df.filter(like='STREET').columns

Index(['STREET Address1', 'STREET Address2', 'STREET Address3'], dtype='str')

In [12]:
# Chọn tên cột với các ký tự cuối trong điều kiện (endswith)
df.loc[:, df.columns.str.endswith('name') | df.columns.str.endswith('Name')].columns

Index(['First Name', 'Last name'], dtype='str')

In [13]:
# Hiện tên cột với ký tự cuối trong điều kiện bằng bộ lọc regex
df.filter(regex='(?i)name$', axis=1).columns

Index(['First Name', 'Last name'], dtype='str')

In [14]:
# Hiện một nhóm tên cột theo chỉ mục slice
df.columns.values[0:4]

<StringArray>
['First Name', 'Last name', 'Date of Birth', 'SALARY']
Length: 4, dtype: str

---
## IV – BÀI TẬP VỀ NHÀ: LÀM SẠCH BỘ DỮ LIỆU BẤT ĐỘNG SẢN (`property_data.csv`)

Bộ dữ liệu trong repository: `https://raw.githubusercontent.com/shizziio/uit-DS200.G11.CN2.TTNT/main/datasets/lab3/property_data.csv`  
Bao gồm các thuộc tính:
- `PID`: Mã định danh bất động sản
- `ST_NUM`: Số nhà (Street Number)
- `ST_NAME`: Tên đường (Street Name)
- `OWN_OCCUPIED`: Đang có chủ ở hay không (Y/N)
- `NUM_BEDROOMS`: Số phòng ngủ
- `NUM_BATH`: Số phòng tắm
- `SQ_FT`: Diện tích (feet vuông)

### 2.1. Đọc tệp csv vào Dataframe
*Lưu ý:* Trong thực tế, dữ liệu khuyết thiếu không chỉ xuất hiện dưới dạng ô trống hoặc `NaN`, mà còn có `n/a`, `na`, `--`. Chúng ta truyền danh sách `na_values` để Pandas nhận diện đồng nhất tất cả thành `NaN`.

In [15]:
# Đọc tệp property_data.csv có xử lý các định dạng missing đặc thù
missing_values = ['n/a', 'na', '--']
df_prop = pd.read_csv(f'{DATASET_BASE_URL}/property_data.csv', na_values=missing_values)
df_prop

           PID  ST_NUM     ST_NAME OWN_OCCUPIED  NUM_BEDROOMS NUM_BATH   SQ_FT
0  100001000.0   104.0      PUTNAM            Y           3.0        1  1000.0
1  100002000.0   197.0   LEXINGTON            N           3.0      1.5     NaN
2  100003000.0     NaN   LEXINGTON            N           NaN        1   850.0
3  100004000.0   201.0    BERKELEY           12           1.0      NaN   700.0
4          NaN   203.0    BERKELEY            Y           3.0        2  1600.0
5  100006000.0   207.0    BERKELEY            Y           NaN        1   800.0
6  100007000.0     NaN  WASHINGTON          NaN           2.0   HURLEY   950.0
7  100008000.0   213.0     TREMONT            Y           1.0        1     NaN
8  100009000.0   215.0     TREMONT            Y           NaN        2  1800.0

### 2.2. Tìm trong Dataframe những dữ liệu bị thiếu
Sử dụng `isnull()` để kiểm tra ma trận boolean và đếm số lượng giá trị thiếu theo từng cột.

In [16]:
# Kiểm tra dữ liệu bị thiếu dạng bảng boolean
df_prop.isnull()

     PID  ST_NUM  ST_NAME  OWN_OCCUPIED  NUM_BEDROOMS  NUM_BATH  SQ_FT
0  False   False    False         False         False     False  False
1  False   False    False         False         False     False   True
2  False    True    False         False          True     False  False
3  False   False    False         False         False      True  False
4   True   False    False         False         False     False  False
5  False   False    False         False          True     False  False
6  False    True    False          True         False     False  False
7  False   False    False         False         False     False   True
8  False   False    False         False          True     False  False

In [17]:
# Thống kê số lượng ô bị thiếu trên từng cột
df_prop.isnull().sum()

PID             1
ST_NUM          2
ST_NAME         0
OWN_OCCUPIED    1
NUM_BEDROOMS    3
NUM_BATH        1
SQ_FT           2
dtype: int64

### 2.3. Xem cột `NUM_BEDROOMS` và tìm những giá trị `NaN`

In [18]:
# Xem giá trị cột NUM_BEDROOMS
print(df_prop['NUM_BEDROOMS'])

# Lọc và hiển thị các dòng có NUM_BEDROOMS là NaN
df_prop[df_prop['NUM_BEDROOMS'].isnull()]

0    3.0
1    3.0
2    NaN
3    1.0
4    3.0
5    NaN
6    2.0
7    1.0
8    NaN
Name: NUM_BEDROOMS, dtype: float64

           PID  ST_NUM    ST_NAME OWN_OCCUPIED  NUM_BEDROOMS NUM_BATH   SQ_FT
2  100003000.0     NaN  LEXINGTON            N           NaN        1   850.0
5  100006000.0   207.0   BERKELEY            Y           NaN        1   800.0
8  100009000.0   215.0    TREMONT            Y           NaN        2  1800.0

### 2.4. Tổng giá trị còn thiếu trong Dataframe
Sử dụng `df.isnull().sum().sum()` để tính tổng toàn bộ ô trống/khuyết trong DataFrame.

In [19]:
total_missing = df_prop.isnull().sum().sum()
print(f"Tổng số giá trị còn thiếu trong toàn bộ Dataframe là: {total_missing}")

Tổng số giá trị còn thiếu trong toàn bộ Dataframe là: 10

### 2.5a. Điền giá trị 126 vào ô bị thiếu trong cột `ST_NUM`

In [20]:
# Điền giá trị 126 vào các ô thiếu trong ST_NUM
df_prop['ST_NUM'] = df_prop['ST_NUM'].fillna(126)
df_prop[['PID', 'ST_NUM', 'ST_NAME']]

           PID  ST_NUM     ST_NAME
0  100001000.0   104.0      PUTNAM
1  100002000.0   197.0   LEXINGTON
2  100003000.0   126.0   LEXINGTON
3  100004000.0   201.0    BERKELEY
4          NaN   203.0    BERKELEY
5  100006000.0   207.0    BERKELEY
6  100007000.0   126.0  WASHINGTON
7  100008000.0   213.0     TREMONT
8  100009000.0   215.0     TREMONT

### 2.5b. Thay thế missing values trong cột `NUM_BEDROOMS` bằng giá trị trung vị (median)

In [21]:
# Tính giá trị trung vị của cột NUM_BEDROOMS
median_bedrooms = df_prop['NUM_BEDROOMS'].median()
print(f"Giá trị median của NUM_BEDROOMS: {median_bedrooms}")

# Thay thế các ô NaN bằng median
df_prop['NUM_BEDROOMS'] = df_prop['NUM_BEDROOMS'].fillna(median_bedrooms)
df_prop[['PID', 'NUM_BEDROOMS']]

Giá trị median của NUM_BEDROOMS: 2.5

           PID  NUM_BEDROOMS
0  100001000.0           3.0
1  100002000.0           3.0
2  100003000.0           2.5
3  100004000.0           1.0
4          NaN           3.0
5  100006000.0           2.5
6  100007000.0           2.0
7  100008000.0           1.0
8  100009000.0           2.5

### Kết quả DataFrame hoàn chỉnh sau khi xử lý:

In [22]:
# Hiển thị DataFrame sau khi hoàn thành làm sạch
df_prop

           PID  ST_NUM     ST_NAME OWN_OCCUPIED  NUM_BEDROOMS NUM_BATH   SQ_FT
0  100001000.0   104.0      PUTNAM            Y           3.0        1  1000.0
1  100002000.0   197.0   LEXINGTON            N           3.0      1.5     NaN
2  100003000.0   126.0   LEXINGTON            N           2.5        1   850.0
3  100004000.0   201.0    BERKELEY           12           1.0      NaN   700.0
4          NaN   203.0    BERKELEY            Y           3.0        2  1600.0
5  100006000.0   207.0    BERKELEY            Y           2.5        1   800.0
6  100007000.0   126.0  WASHINGTON          NaN           2.0   HURLEY   950.0
7  100008000.0   213.0     TREMONT            Y           1.0        1     NaN
8  100009000.0   215.0     TREMONT            Y           2.5        2  1800.0